### ISSUE TITLE
pidusage.stat pidusage.stat is not a function

### ISSUE THREAD

**Issue by Wesseldr** [ziyasal/hapijs-status-monitor#27]
Hi,
Thank you for this great tool 👍 
I was testing the current master commit
The current commit: 1ddc160b337eb0c9e9daf1f00b726aa095bfc1f7
```
"hapijs-status-monitor": {
      "version": "git+https://github.com/ziyasal/hapijs-status-monitor.git#1ddc160b337eb0c9e9daf1f00b726aa095bfc1f7",
      "requires": {
        "pidusage": "2.0.6",
        "socket.io": "2.1.0"
      }
},
```
And it looks like it fails on:

```
/node_modules/hapijs-status-monitor/src/helpers/gather-os-metrics.js:16
  pidusage.stat(process.pid, (err, stat) => {
           ^
TypeError: pidusage.stat is not a function
    at module.exports (/Users/wessel/Development/VitalTracker/reporting-services/node_modules/hapijs-status-monitor/src/helpers/gather-os-metrics.js:16:12)
    at Timeout.setInterval [as _onTimeout] (/Users/wessel/Development/VitalTracker/reporting-services/node_modules/hapijs-status-monitor/src/helpers/socket-io-init.js:24:42)
    at ontimeout (timers.js:458:11)
    at Timer.unrefdHandle (timers.js:570:5)

```
I think it's a code breaking change in the pidusage from 1.x to 2.x that no longer makes the pidusage.stat available, I will create a little pull RQ

Regards,

**Comment by Wesseldr** [comment]
added a pull request, enjoy
