### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by immontilla** [ziyasal/hapijs-status-monitor#29]
Hello,

I'm using node 9.2.0 and npm 6.1.0.

I got this message when I ran the example.
```
module.js:544
    throw err;
    ^

Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mauricio/git/hapijs-status-monitor/src/helpers/socket-io-init.js:3:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hapijs-status-monitor-sample@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hapijs-status-monitor-sample@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
Afterwards, in the package.json file, I changed "file:../" to "0.6.0", and I got this error
```
{ AssertionError [ERR_ASSERTION]: Invalid plugin options {
  "plugin": {
    "register": (server, options, next) => {\n  const opts = validate(options);\n\n  // Setup Socket.IO\n  server.on('start', () => {\n    socketIoInit(server.listener, opts.spans);\n  });\n\n  server.route({\n    method: 'GET',\n    path: opts.path,\n    handler: (request, reply) => {\n      const renderedHtml =\n        fs.readFileSync(path.join(__dirname, '/public/index.html'))\n          .toString()\n          .replace(/{{title}}/g, opts.title)\n          .replace(/{{script}}/g, fs.readFileSync(path.join(__dirname, '/public/javascripts/app.js')))\n          .replace(/{{style}}/g, fs.readFileSync(path.join(__dirname, '/public/stylesheets/style.css')));\n\n      reply(renderedHtml)\n        .header('Content-Type', 'text/html')\n        .code(200);\n    },\n    config: opts.routeConfig,\n  });\n\n  // Hook into the middle of processing\n  server.ext('onPreResponse', (request, reply) => {\n    if (request.response.isBoom || request.path === opts.path) {\n      return reply.continue();\n    }\n\n    const startTime = process.hrtime();\n    const resp = request.response;\n\n    resp.once('finish', () => {\n      onHeadersListener(resp.statusCode, startTime, opts.spans);\n    });\n\n    return reply.continue();\n  });\n\n  // Continue processing\n  return next();\n},
    "name" [1]: -- missing --
  }
}

[1] "name" is required
    at Object.exports.apply (/home/mauricio/git/hapijs-status-monitor/examples/node_modules/hapi/lib/config.js:22:10)
    at internals.Server.register (/home/mauricio/git/hapijs-status-monitor/examples/node_modules/hapi/lib/server.js:399:31)
    at start (/home/mauricio/git/hapijs-status-monitor/examples/server.js:24:18)
    at Object.<anonymous> (/home/mauricio/git/hapijs-status-monitor/examples/server.js:35:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```
Honestly, I'm not sure if this is an issue or I'm missing something.

Thanks in advance,

Ivan

**Comment by jeremyrajan** [comment]
I get the same as well, integration doesnt seem to work. 
![image](https://user-images.githubusercontent.com/2890683/43034859-ff26db5c-8d16-11e8-9911-34f438d462ae.png)

Node: v10.7.0,
NPM: 6.1.0
Hapi: ^17.5.2
hapijs-status-monitor: ^0.6.0

**Comment by jeremyrajan** [comment]
I get the same as well,

![image](https://user-images.githubusercontent.com/2890683/43034883-65cd2f00-8d17-11e8-84f1-6ae999a48cfd.png)

Node: 10.7.0
NPM: 6.1.0
"hapi": "^17.5.2"
"hapijs-status-monitor": "^0.6.0"

**Comment by jeremyrajan** [comment]
@immontilla Seems like NPM has a older version published compared to whats on master. On NPM its `0.6.0` and current version is `1.0.0`. It would be best if the contributors update the plugin with latest version on NPM, otherwise they will get above errors. 

In the mean time, you can point your package to github repo. That should pickup the latest version for now.

![image](https://user-images.githubusercontent.com/2890683/43034927-2c762abc-8d18-11e8-94cd-db9db1fb8615.png)

Hope that helps :).

**Comment by immontilla** [comment]
Thanks!!! @jeremyrajan 
"hapijs-status-monitor": "ziyasal/hapijs-status-monitor" did the trick.
As you said the real solution is update the plugin on NPM.

**Comment by cdll** [comment]
same issue here with npm installed `+ hapijs-status-monitor@0.6.0`~

**Comment by danielbayerlein** [comment]
Version 1.0.0 is now released. See also #26
